import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    backgroundColor: '#007AFF',
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingVertical: 30,
  },
  emptyState: {
    backgroundColor: '#D3D3D3',
    marginHorizontal: 30,
    marginTop: 20,
    padding: 40,
    borderRadius: 8,
    alignItems: 'center',
  },
  emptyStateText: {
    color: '#333',
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
  },
  addButton: {
    backgroundColor: '#007AFF',
    marginHorizontal: 50,
    marginBottom: 30,
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: 'center',
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  formContainer: {
    backgroundColor: '#D3D3D3',
    marginHorizontal: 20,
    marginTop: 20,
    padding: 25,
    borderRadius: 15,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  clienteSelectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    gap: 8,
  },
  clienteSelectedText: {
    fontSize: 15,
    color: '#007AFF',
    fontWeight: '600',
  },
  exerciciosListContainer: {
    marginBottom: 15,
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 15,
  },
  exerciciosListTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#00C853',
    marginBottom: 10,
  },
  exercicioAddedCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#00C853',
  },
  exercicioAddedContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  exercicioAddedInfo: {
    flex: 1,
  },
  exercicioAddedNome: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  exercicioAddedDetalhes: {
    fontSize: 13,
    color: '#666',
    marginBottom: 6,
  },
  diaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  diaBadgeText: {
    fontSize: 11,
    color: '#007AFF',
    fontWeight: '600',
  },
  exercicioActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editExercicioButton: {
    backgroundColor: '#FFF3E0',
    padding: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteExercicioButton: {
    backgroundColor: '#FFEBEE',
    padding: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  addExercicioButton: {
    flex: 1,
    backgroundColor: '#007AFF',
    borderRadius: 10,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  addExercicioButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  inputGroup: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 14,
    color: '#007AFF',
    marginBottom: 5,
    fontWeight: '500',
  },
  input: {
    backgroundColor: '#e9e9e9ff',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#000',
  },
  concludeButton: {
    backgroundColor: '#00C853',
    borderRadius: 25,
    paddingVertical: 15,
    marginTop: 20,
    alignItems: 'center',
  },
  concludeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  clientsListContainer: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  clientCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  clientInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  clientInfo: {
    flex: 1,
  },
  clientLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  clientValue: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  treinoClientCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  treinoClientInfo: {
    width: '100%',
  },
  clientInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  treinoClientLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  treinoClientValue: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  montarTreinoButton: {
    backgroundColor: '#007AFF',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  montarTreinoButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  treinoInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  treinoInputSmall: {
    flex: 1,
  },
  treinosListContainer: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  treinoCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  treinoCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#007AFF',
    flex: 1,
  },
  treinoCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  treinoCardActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editTreinoCardButton: {
    backgroundColor: '#FFF3E0',
    padding: 8,
    borderRadius: 8,
  },
  deleteTreinoCardButton: {
    backgroundColor: '#FFEBEE',
    padding: 8,
    borderRadius: 8,
  },
  exercicioCount: {
    fontSize: 13,
    color: '#666',
    marginBottom: 12,
  },
  exercicioItem: {
    backgroundColor: '#F5F5F5',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  exercicioItemContent: {
    gap: 4,
  },
  exercicioText: {
    fontSize: 15,
    color: '#333',
    fontWeight: '600',
  },
  exercicioDetails: {
    fontSize: 13,
    color: '#666',
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#007AFF',
    paddingTop: 15,
    paddingBottom: 45,
    borderTopWidth: 1,
    borderTopColor: '#0066CC',
  },
  navButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonActive: {
    backgroundColor: 'transparent',
  },
  navButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  navButtonTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxHeight: '85%',
    backgroundColor: '#fff',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalScroll: {
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#007AFF',
  },
  closeButton: {
    padding: 5,
  },
  modalButtonsContainer: {
    marginTop: 25,
    marginBottom: 15,
  },
  treinoActionsContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  editarTreinoButton: {
    flex: 1,
    backgroundColor: '#FF9800',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  editarTreinoButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  mostrarTreinoButton: {
    flex: 1,
    backgroundColor: '#00C853',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  mostrarTreinoButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  diasSemanaContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 5,
  },
  diaButton: {
    backgroundColor: '#E0E0E0',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  diaButtonActive: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  diaButtonText: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  diaButtonTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  treinosAtuaisContainer: {
    backgroundColor: '#FFF9E6',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
  },
  treinosAtuaisTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF9800',
    marginBottom: 12,
  },
  treinoAtualCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#FF9800',
  },
  treinoAtualHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  treinoAtualNome: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  deleteTreinoAtualButton: {
    backgroundColor: '#FFEBEE',
    padding: 6,
    borderRadius: 6,
  },
  treinoAtualExercicios: {
    fontSize: 12,
    color: '#666',
  },
  selecaoTreinosTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 15,
    marginTop: 10,
  },
  emptyBiblioteca: {
    alignItems: 'center',
    padding: 40,
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    marginBottom: 20,
  },
  emptyBibliotecaText: {
    fontSize: 16,
    color: '#666',
    marginTop: 15,
    fontWeight: '600',
  },
  emptyBibliotecaSubtext: {
    fontSize: 14,
    color: '#999',
    marginTop: 5,
  },
  treinosPadraoList: {
    gap: 10,
    marginBottom: 20,
  },
  treinoPadraoCard: {
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 15,
    borderWidth: 2,
    borderColor: '#E0E0E0',
  },
  treinoPadraoCardSelected: {
    backgroundColor: '#E3F2FD',
    borderColor: '#007AFF',
  },
  treinoPadraoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 6,
  },
  treinoPadraoNome: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  treinoPadraoExercicios: {
    fontSize: 13,
    color: '#666',
    marginLeft: 36,
  },
});

export default styles;
